# Generated by Django 4.2.17 on 2024-12-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bar_code", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("nutri_score", models.IntegerField()),
                ("nutri_class", models.CharField(max_length=255)),
                ("nutrient_data", models.JSONField()),
                ("ingredient_data", models.TextField()),
                ("nova_group", models.IntegerField()),
                ("nova_summary", models.CharField(max_length=255)),
                ("eco_score", models.CharField(max_length=255)),
                ("sustainability_summary", models.CharField(max_length=255)),
                ("palmoil", models.CharField(max_length=255)),
                ("vegetarian", models.CharField(max_length=255)),
            ],
        ),
    ]
