# Generated by Django 4.2.17 on 2024-12-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="username",
            field=models.TextField(default="arseven"),
            preserve_default=False,
        ),
    ]
